server:
  port: 8081

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${PGUSER}       # "postgres" (default in Railway)
    password: ${PGPASSWORD}   # Railway auto-generates this
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.springframework.jdbc.datasource: DEBUG
