server:
  port: 8081

spring:
  application:
    name: customer-service

  datasource:
    url: 9f3ef314-c474-4914-98f4-4dc49f175568.DATABASE_URL
    username: postgres
    password: test123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
