server:
  port: 8081

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=disable
    username: ${PGUSER}       # "postgres" (default)
    password: ${PGPASSWORD}   # Railway auto-generates this
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.springframework.jdbc.datasource: DEBUG
