server:
  port: 8081

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=disable  # Railway provides these vars
    username: ${PGUSER}       # Railway provides this (default: "postgres")
    password: ${PGPASSWORD}   # Railway provides this    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
