server:
  port: 8081

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://${DATABASE_URL}  # Railway provides these vars

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
